---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .ObjectMeta.Name }}
  namespace: {{ .ObjectMeta.Namespace }}
spec:
  template:
    spec:
      backoffLimit: 6
      restartPolicy: OnFailure
      containers:
        - command:
            - /bin/bash
            - -c
            - /usr/local/bin/upload
          image: quay.io/redhat-cop/must-gather-operator:latest
          name: upload
          volumeMounts:
            - mountPath: /must-gather
              name: must-gather-output
            - mountPath: /must-gather-upload
              name: must-gather-upload
          env:
            {{ if .Spec.ProxyConfig.HTTPProxy -}}
            - name: http_proxy
              value: {{ .Spec.ProxyConfig.HTTPProxy }}
            {{ end -}}
            {{ if .Spec.ProxyConfig.HTTPSProxy -}}
            - name: https_proxy
              value: {{ .Spec.ProxyConfig.HTTPSProxy }}
            {{ end -}}
            {{ if .Spec.ProxyConfig.NoProxy -}}
            - name: no_proxy
              value: {{ .Spec.ProxyConfig.NoProxy }}
            {{ end -}}
            - name: username
              valueFrom:
                secretKeyRef:
                  name: {{ .Spec.CaseManagementAccountSecretRef.Name }}
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: {{ .Spec.CaseManagementAccountSecretRef.Name }}
                  key: password
            - name: caseid
              value: "{{ .Spec.CaseID }}"
            - name: must_gather_output
              value: /must-gather
            - name: must_gather_upload
              value: /must-gather-upload
      initContainers:
{{- range $index, $element := .Spec.MustGatherImages }}
        - command:
            - /usr/bin/gather
          image: {{ $element }}
          name: gather-{{ $index }}
          volumeMounts:
            - mountPath: /must-gather
              name: must-gather-output
{{- end }}
{{- range $index, $element := .Spec.MustGatherImagesWithParameters }}
        - image: {{ $element.Image }}
          name: gather-wp-{{ $index }}
          command:
            {{- range $cindex, $cmd := $element.Command }}
            - {{ $cmd }}
            {{- end }}
          args:
            {{- range $aindex, $arg := $element.Args }}
            - {{ $arg }}
            {{- end }}
          workingDir: {{ $element.WorkingDir }}
          envFrom:
          {{- range $envfromindex, $envFrom := $element.EnvFrom }}
          - prefix: {{ $envFrom.Prefix }}
            {{ if $envFrom.ConfigMapRef -}}
            configMapRef:
              name: {{ $envFrom.ConfigMapRef.Name }}
              optional: {{ if $envFrom.ConfigMapRef.Optional -}}{{ $envFrom.ConfigMapRef.Optional }}{{ end }}
            {{ end }}
            {{ if $envFrom.SecretRef -}}
            secretRef:
              name: {{ if $envFrom.SecretRef -}}{{ $envFrom.SecretRef.Name }}{{ end }}
              optional: {{ if $envFrom.SecretRef.Optional -}}{{ $envFrom.SecretRef.Optional }}{{ end }}
            {{ end }}
          {{- end }}
          env:
          {{- range $envindex, $env := $element.Env }}
            - name: {{ $env.Name }}
              value: {{ $env.Value }}
              {{ if $env.ValueFrom -}}
              valueFrom:
                fieldRef:
                  apiVersion: {{ if $env.ValueFrom.FieldRef -}}{{ $env.ValueFrom.FieldRef.APIVersion }}{{ end }}
                  fieldPath: {{ if $env.ValueFrom.FieldRef -}}{{ $env.ValueFrom.FieldRef.FieldPath }}{{ end }}
                resourceFieldRef:
                  containerName: {{ if $env.ValueFrom.ResourceFieldRef -}}{{ $env.ValueFrom.ResourceFieldRef.ContainerName }}{{ end }}
                  resource: {{ if $env.ValueFrom.ResourceFieldRef -}}{{ $env.ValueFrom.ResourceFieldRef.Resource }}{{ end }}
                  divisor: {{ if $env.ValueFrom.ResourceFieldRef -}}{{ $env.ValueFrom.ResourceFieldRef.Divisor }}{{ end }}
                configMapKeyRef:
                  name: {{ if $env.ValueFrom.ConfigMapKeyRef -}}{{ $env.ValueFrom.ConfigMapKeyRef.Name }}{{ end }}
                  key: {{ if $env.ValueFrom.ConfigMapKeyRef -}}{{ $env.ValueFrom.ConfigMapKeyRef.Key }}{{ end }}
                  optional: {{ if $env.ValueFrom.ConfigMapKeyRef -}}{{ $env.ValueFrom.ConfigMapKeyRef.Optional }}{{ end }}
                secretKeyRef:
                  name: {{ if $env.ValueFrom.SecretKeyRef -}}{{ $env.ValueFrom.SecretKeyRef.Name }}{{ end }}
                  key: {{ if $env.ValueFrom.SecretKeyRef -}}{{ $env.ValueFrom.SecretKeyRef.Key }}{{ end }}
                  optional: {{ if $env.ValueFrom.SecretKeyRef -}}{{ $env.ValueFrom.SecretKeyRef.Optional }}{{ end }}
              {{ end }}
          {{- end }}
          volumeMounts:
            - mountPath: /must-gather
              name: must-gather-output
{{- end }}
      serviceAccountName: {{ .Spec.ServiceAccountRef.Name }}
      volumes:
      - emptyDir: {}
        name: must-gather-output
      - emptyDir: {}
        name: must-gather-upload
